import { Request, Response, NextFunction } from 'express';
import { ReportService } from '../services/reportService';
import { ExportService } from '../services/exportService';
import prisma from '../config/db';
import { AppError } from '../utils/AppError';
import { Role } from '@prisma/client';

const reportService = new ReportService();
const exportService = new ExportService();

export const generateReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.id;
    const role = req.user!.role as Role;
    const { type, projectId, employeeId, startDate, endDate, exportFormat } = req.body;

    if (!type) {
      return next(new AppError('Report type is required.', 400));
    }

    const report = await reportService.generateReport(userId, role, type, {
      projectId,
      employeeId,
      startDate: startDate ? new Date(startDate) : undefined,
      endDate: endDate ? new Date(endDate) : undefined
    });

    // If export is requested directly
    if (exportFormat) {
      const format = String(exportFormat).toLowerCase();
      if (format === 'csv') {
        const csv = exportService.convertToCSV([{
          Title: report.title,
          Type: report.type,
          GeneratedAt: report.createdAt.toISOString(),
          Content: report.content
        }]);
        res.setHeader('Content-Type', 'text/csv');
        res.setHeader('Content-Disposition', `attachment; filename=report_${report.id}.csv`);
        return res.status(200).send(csv);
      } 
      else if (format === 'excel') {
        const excel = exportService.convertToExcelHTML([{
          Title: report.title,
          Type: report.type,
          GeneratedAt: report.createdAt.toISOString(),
          Content: report.content
        }], 'Report Output');
        res.setHeader('Content-Type', 'application/vnd.ms-excel');
        res.setHeader('Content-Disposition', `attachment; filename=report_${report.id}.xls`);
        return res.status(200).send(excel);
      } 
      else if (format === 'pdf') {
        const pdfHtml = exportService.convertToPDFHtml(report.title, report.content);
        res.setHeader('Content-Type', 'text/html');
        return res.status(200).send(pdfHtml);
      }
    }

    res.status(201).json({
      status: 'success',
      data: { report }
    });
  } catch (error) {
    next(error);
  }
};

export const getReports = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.id;
    const role = req.user!.role;

    // Fetch reports generated by this user or reports inside projects this user has access to
    const projects = await prisma.project.findMany({
      where: {
        OR: [
          { managerId: userId },
          { members: { some: { userId } } }
        ]
      },
      select: { id: true }
    });

    const projectIds = projects.map(p => p.id);

    const reports = await prisma.generatedReport.findMany({
      where: {
        OR: [
          { generatedBy: userId },
          { projectId: { in: projectIds } }
        ]
      },
      include: {
        creator: { select: { id: true, name: true } },
        project: { select: { name: true, code: true } }
      },
      orderBy: { createdAt: 'desc' }
    });

    res.status(200).json({
      status: 'success',
      data: { reports }
    });
  } catch (error) {
    next(error);
  }
};

export const downloadReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const format = String(req.query.format || 'pdf').toLowerCase();

    const report = await prisma.generatedReport.findUnique({
      where: { id },
      include: { project: true }
    });

    if (!report) {
      return next(new AppError('Report not found', 404));
    }

    if (format === 'csv') {
      const csv = exportService.convertToCSV([{
        Title: report.title,
        Type: report.type,
        GeneratedAt: report.createdAt.toISOString(),
        Content: report.content
      }]);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=report_${report.id}.csv`);
      return res.status(200).send(csv);
    } 
    else if (format === 'excel') {
      const excel = exportService.convertToExcelHTML([{
        Title: report.title,
        Type: report.type,
        GeneratedAt: report.createdAt.toISOString(),
        Content: report.content
      }], 'Report Details');
      res.setHeader('Content-Type', 'application/vnd.ms-excel');
      res.setHeader('Content-Disposition', `attachment; filename=report_${report.id}.xls`);
      return res.status(200).send(excel);
    } 
    else {
      // PDF mode returns standard printable HTML template
      const pdfHtml = exportService.convertToPDFHtml(report.title, report.content);
      res.setHeader('Content-Type', 'text/html');
      return res.status(200).send(pdfHtml);
    }
  } catch (error) {
    next(error);
  }
};

export default {
  generateReport,
  getReports,
  downloadReport
};
