import React from 'react';
import Card from './Card';
import MarkdownRenderer from './MarkdownRenderer';
import { CheckSquare } from 'lucide-react';

export const SummaryCard = ({ report, onGenerateTasks, loadingTasks = false }) => {
  if (!report) return null;

  return (
    <div className="space-y-4 font-sans text-xs">
      <Card title={report.title} subtitle={`Generated by AI on ${new Date(report.createdAt).toLocaleDateString()}`}>
        <div className="space-y-4">
          <MarkdownRenderer content={report.content} />
          
          {onGenerateTasks && (
            <div className="flex justify-end pt-3 border-t border-slate-100">
              <button
                disabled={loadingTasks}
                onClick={() => onGenerateTasks(report.content)}
                className="px-4 py-2 bg-indigo-650 hover:bg-indigo-750 disabled:bg-slate-200 text-white disabled:text-slate-400 font-bold rounded-lg cursor-pointer transition-colors flex items-center gap-1.5 shadow-xs"
              >
                <CheckSquare className="h-4 w-4" />
                <span>{loadingTasks ? 'Structuring Tasks...' : 'Generate Tasks from Summary'}</span>
              </button>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
};

export default SummaryCard;
